/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as SettingsRouteImport } from './../routes/settings'
import { Route as LiveFeedRouteImport } from './../routes/live-feed'
import { Route as LabelingRouteImport } from './../routes/labeling'
import { Route as DashboardRouteImport } from './../routes/dashboard'
import { Route as IndexRouteImport } from './../routes/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveFeedRoute = LiveFeedRouteImport.update({
  id: '/live-feed',
  path: '/live-feed',
  getParentRoute: () => rootRouteImport,
} as any)
const LabelingRoute = LabelingRouteImport.update({
  id: '/labeling',
  path: '/labeling',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/labeling': typeof LabelingRoute
  '/live-feed': typeof LiveFeedRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/labeling': typeof LabelingRoute
  '/live-feed': typeof LiveFeedRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/labeling': typeof LabelingRoute
  '/live-feed': typeof LiveFeedRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/labeling' | '/live-feed' | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/labeling' | '/live-feed' | '/settings'
  id: '__root__' | '/' | '/dashboard' | '/labeling' | '/live-feed' | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LabelingRoute: typeof LabelingRoute
  LiveFeedRoute: typeof LiveFeedRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-feed': {
      id: '/live-feed'
      path: '/live-feed'
      fullPath: '/live-feed'
      preLoaderRoute: typeof LiveFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labeling': {
      id: '/labeling'
      path: '/labeling'
      fullPath: '/labeling'
      preLoaderRoute: typeof LabelingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LabelingRoute: LabelingRoute,
  LiveFeedRoute: LiveFeedRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
